### PR TITLE
Links to apsimx doco should be https.

### PR DESCRIPTION
**Pull request by hol430**

### CODE REVIEW

**Comment by hol353** [comment]
This is changing code that isn't used anymore. The method GetDocumentationHTMLForVersion is used instead.

**Comment by hol430** [comment]
Oh ok - well perhaps we should remove this method altogether then?

**Comment by hol430** [comment]
Also - where does the index.html in the releases directory come from?

**Comment by hol353** [comment]
Yes we can remove the method now. I've created a new project in the APSIMx solution called CreateDocmentation. This project creates all auto-docs and the index.html file. I've modified the jenkins file to call this assembly. You've given me the clue I needed. In my PR a few minutes ago i changed from http links to https links. Hopefully that will fix the problem.

**Comment by hol353** [comment]
Can you also remove it from IBuilds.cs

**Pull request merged**
